version: '3.8'

services:
    mysql:
        image: mysql:8.0.34
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: my-db
        volumes:
            - mysql-volume:/var/lib/mysql

volumes:
    mysql-volume: